# Generated by Django 6.1 on 2026-08-24 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.Field(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dịch vụ')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá cơ bản (VND)')),
                ('estimated_time', models.PositiveIntegerField(default=60, help_text='Thời gian dự kiến thi công (phút)')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(verbose_name='Thời gian hẹn')),
                ('address', models.TextField(verbose_name='Địa chỉ thi công')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú của khách')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype', verbose_name='Dịch vụ')),
            ],
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completion_notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú sau khi hoàn thành')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='services.booking')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Thợ phụ trách')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá bán (VND)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='services.category')),
            ],
        ),
    ]
